$(function(){
  $("#header").load("header.html"); 
  $("#footer").load("footer.html"); 
});
$(function(){
  $("#headerOne").load("headerOne.html"); 
});
$(function(){ 
  $("#homefooter").load("homefooter.html"); 
});